# Generated by Django 4.0.4 on 2022-05-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theatr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='theatr')),
                ('photo_detail', models.ImageField(blank=True, upload_to='theatr')),
                ('director', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('age', models.CharField(max_length=255)),
                ('premiere_date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
