# Generated by Django 4.0.4 on 2022-05-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_theatr'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.theatr', to_field='title')),
                ('seat', models.ManyToManyField(blank=True, to='cinema.seat')),
            ],
            options={
                'verbose_name_plural': 'Сеансы',
            },
        ),
    ]
