# Generated by Django 4.0.4 on 2022-05-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_tseans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tseans',
            options={'verbose_name_plural': 'Сеансы театра'},
        ),
    ]
