# Generated by Django 4.0.4 on 2022-05-30 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_tseans_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tseans',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.theatr', to_field='title'),
        ),
    ]
